### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by cwfoo** [dbakker/vim-paragraph-motion#1]
Could you add license information for this plugin?

**Comment by dbakker** [comment]
Done! I put the license of the original code this plugin is based on.

**Comment by cwfoo** [comment]
Thank you for the fix.

I understand that you don't have control over the license because the original code comes from inactive stackoverflow.com users, but I am just a bit concerned that a CC license is not really suitable for Vim plugins.

I have implemented a similar plugin: https://github.com/cwfoo/vim-paramotion It turns out that my implementation is similar to the one in this repository. Perhaps that is a tell-tale sign that this could be considered "trivial code", where there aren't many different ways of implementing the same idea. I found this repository useful for verifying the behavior of my implementation.

A few questions:

1. It seems that this repository was made to make it convenient for users to download https://stackoverflow.com/a/2777488 using their Vim package manager. I have found a few mistakes in that answer (and in this repository). Do you accept patches?
2. What is your view on the non-ideal license issue?

**Comment by dbakker** [comment]
Thanks for your explanation!

1. I'm happy to accept patches.
2. I can see the "trivial code" rationale. Shall I update it to the 0BSD license?

**Comment by cwfoo** [comment]
>  Shall I update it to the 0BSD license?

That would be great. I think it is safe to do so.

Please give me some time to prepare the patches.
