### ISSUE TITLE
windows line endings

### ISSUE THREAD

**Issue by wnim** [dbakker/vim-paragraph-motion#12]
i had to run
dos2unix on ipmotion.vim to avoid these error messages:

```
Error detected while processing /home/nweinberg/.vim/plugged/Improved-paragraph-motion/plugin/ipmotion.vim:
line   50:
E492: Not an editor command: ^M
line   51:
E488: Trailing characters: ^M
line  145:
E171: Missing :endif
Press ENTER or type command to continue
```

**Comment by dbakker** [comment]
Hi,

1. That is a different plugin than this one
2. The line endings are dependent on your gitconfig, [you need to modify your gitconfig](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings) so that it appends the proper endings
